### ISSUE TITLE
Bracket layers

### ISSUE THREAD

**Issue by arialcrime** [yanone/SpaceBar30DayTrial#1]
Hey, 

I just gave the trial a quick spin and I found that Space Bar does not handle alternative shape layers – neither the traditional setup, nor reverse bracket layers. Considering the possibility of a bracket layer having different/wrong side bearings, it would be great to also see them in the graphic visualisations. 

Maybe they can even be shown within the graph of the “normal” layers to make it easier to debug errors.

**Comment by yanone** [comment]
It handles brace layers. I’ll take a look at how to integrate bracket layers. Thank you.

**Comment by yanone** [comment]
Just released a version with bracket layer support. Update via the Plugin Manager (remove & reinstall for instant update)

**Comment by guidoferreyra** [comment]
Hi! I write here because is partially related.
Brace Layers are not indicated on interpolation Space?

**Comment by yanone** [comment]
Not at the moment. The interpolation space panel is font-specific, not glyph-specific, and is supposed to show the weight increase of the defined instances. The same curve characteristic seen there should then be resembled, so far the idea, in the glyph-specific values and curves.

I thought that showing brace layers only with the glyph-specific panels is sufficient because different glyphs can have brace layers at different positions.

This being said, the indication of masters is sketchy at best, because it's really difficult for me to calculate their importance for each instance. The main problem is that the panels are one-dimensional (per single value) while the interpolation space in Glyphs is three-dimensional. So masters can only be indicated anyway where instances are influenced by one or two masters, meaning a master is either identical to an instance or a master sits right between two instances, sharing two out of the three possible axes with the neighboring instances.
